### ISSUE TITLE
animdl config wrapper

### ISSUE THREAD

**Issue by justchokingaround** [anma-dev/Anime-Manager#1]
hi, great project, quite impressive that you put this all together, i respect your effort! i will be honest i haven't checked the whole codebase just yet, but from what i've seen it doesn't seem like there's an options/menu/selection thingy where you can easily edit some basic animdl settings using its config file: `config.yml`. thought i would share this wrapper i made a while ago (code is a bit old (:skull:), but it might be somewhat helpful as a starting point ig) in case you ever want to add something like this to the project
https://github.com/justchokingaround/animdlconfig-wrapper/blob/main/animdlconfig.sh

keep up the good work, good job so far :)

**Comment by anma-dev** [comment]
Thanks for opening an issue! and thanks for your compliments. I indeed have dedicated some time to this project :) I checked your link it looks like a useful way to configure your animdl configuration file. 

I understand you want anime manager to customize your current animdl configuration file. I think this problem relates to how we onboard current animdl users into anime manager and ensuring they have a similar experience for streaming.

Anime manager currently uses custom media player settings for controlling the playback (https://github.com/anma-dev/Anime-Manager/wiki/Development#media-player-configuration). The project is currently using the environment variable to specify its own animdl configuration file so it overrides any other configuration the user might have for animdl. This way we ensure that at least when using anime manager the users can expect consistent behavior. Animdl does not automatically merge different configurations so the custom user configuration are not taken into account when anime manager starts animdl. If we want anime manager to use both its required settings and the custom user configuration we need to find a way to merge both configurations. But there is an issue with this because the user might be using a custom animdl configuration file location so we might not be able to find it. What I have in mind is to allow the user to pass their animdl configuration file location to anime manager and internally merge both configurations and ensure the required configuration for media player control is set. From that point I could let the user customize this megerd configuration with something like the script you shared above and persistently save it to the user account folder. 

Let me know what you think about this!

**Comment by justchokingaround** [comment]
in my opinion, there is no need to merge the 2 configs for animdl, just being able to quickly edit the one used for AM should be reasonable

**Comment by anma-dev** [comment]
I think they are not mutually exclusive. we can have both merging the configuration and allowing the user to quickly edit it. if the user does not pass a configuration file it just wouldn't merge anything and the editing would be done on a separate configuration file.

**Comment by justchokingaround** [comment]
ohhh ok, i see. then yes, that would be a great move, allows for more freedom :+1:

**Comment by anma-dev** [comment]
opened a pull request let me know what you think

**Comment by justchokingaround** [comment]
looks good, nothing to add really

**Comment by justchokingaround** [comment]
🥰
